### ISSUE TITLE
clean duplicate nodes slow

### ISSUE THREAD

**Issue by robbykraft** [robbykraft/Origami#1]
in planarGraph:
cleanDuplicateNodes() function is perhaps one of the slowest functions. it's the reason fragment() runs slowly.

cursory glance, clean duplicate nodes includes:
- (n³ nodes) search all nodes for match, merge matched nodes
- (n edges) clean circular edges, (n² edges) clean duplicate edges

**Comment by andrew-codes** [comment]
I'm going to take a look at this shortly. If I have any questions, I'll be sure to ask.
