### ISSUE TITLE
on trying examples/wiggle.html, nearest is not defined

### ISSUE THREAD

**Issue by dozingpip** [robbykraft/Origami#21]
When trying examples/wiggle/wiggle.html I don't see any wiggling and the inspector gives an error about nearest being undefined, and upon looking at wiggle.js, yeah I'm not sure where nearest should be coming from...

**Comment by freestraws** [comment]
ps: Love this project by the way!  I'm making an origami based puzzle game, and this library looks very useful for that especially since I was already looking into using the FOLD spec for storing info about models in the game.

**Comment by robbykraft** [comment]
Sincerest apologies for not being responsive.
In the last 2 years the library underwent a complete rewrite. the wiggle example didn't get carried over but it potentially could. it was an experiment that needed more mathematical rigor.

here is a permanent link to the place in the source code
https://github.com/robbykraft/Origami/blob/bbb832271556518bfbf6da35ad207aa43b11e78c/src/kawasaki/index.js#L109

i wouldn't need to worry about the actual bug you are pointing out as the interface has been completely rewritten.

i'll point it out on this thread if i reintroduce the wiggle concept again.

thank you and sorry again!
