### ISSUE TITLE
Behaviour of RayReflectRepeat does not completely model real crease propagation

### ISSUE THREAD

**Issue by starwarigami** [robbykraft/Origami#24]
1. Crease does not propagate as expected through intersections - reflects through first line instead of following Kawaski's theorem
2. Ray should not reflect through a crease if intersection lies on the boundary

**Comment by starwarigami** [comment]
The correct solution to this seems to be to propagate straight through the intersection (or line end point). I don't think Kawaski's theorem applies in this case. Could add an optional flag to terminate at intersections instead of pass through, which may be useful for certain applications

**Comment by starwarigami** [comment]
Ignore previous comment - it is patently false

**Comment by robbykraft** [comment]
this is actually a feature now!
the solution involves folding the faces via faces_matrix and testing line-face intersection against the new face. or, the opposite, reflecting the line via the inverse of each face's matrix and testing again; the latter is how this library does it in "flat fold"

https://github.com/robbykraft/Origami/blob/master/src/graph/flat_fold/index.js
