### ISSUE TITLE
Demo example and build not working

### ISSUE THREAD

**Issue by adelin-b** [robbykraft/Origami#25]
Hello, I just found this repository and I was happy to see it seemed to be very active.
However my first steps are quite not very user-friendly
Here is 2 bugs I found:
```
git clone https://github.com/robbykraft/Origami.git
Cloning into 'Origami'...
remote: Enumerating objects: 84, done.
remote: Counting objects: 100% (84/84), done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 8645 (delta 40), reused 72 (delta 30), pack-reused 8561
Receiving objects: 100% (8645/8645), 9.15 MiB | 7.23 MiB/s, done.
Resolving deltas: 100% (6376/6376), done.
~ ❯ cd Origami
Origami - master ❯ rollup -c

src/index.js → rabbit-ear.js...
[!] Error: Could not resolve './Graph' from src/Folder.js
Error: Could not resolve './Graph' from src/Folder.js
    at error (/usr/local/lib/node_modules/rollup/dist/rollup.js:3460:30)
    at /usr/local/lib/node_modules/rollup/dist/rollup.js:21855:25
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

Origami - master ❯ 

```

src/Folder.js is calling ./Graph.js instead or ./graph.js I guess it should be named correctly

and second error when following the demo tutorial at the second step https://rabbitear.org/download.php

>  Let's put a crease into the piece of paper and ask the software to fold it.
> 
> Erase everything inside of sketch.js, and replace it with:
> 
> ```
> var cp = new CreasePattern();
> cp.crease(0, 0, 0.5, 1).valley();
> new OrigamiPaper(cp);
> ```

```
Uncaught Error: Cannot create CanvasView with the provided argument: [object Object]
    at new initialize (paper-full.min.js:formatted:9009)
    at Function.create (paper-full.min.js:formatted:8796)
    at new initialize (paper-full.min.js:formatted:1930)
    at at.setup (paper-full.min.js:formatted:615)
    at new OrigamiPaper (cp.paperjs.js:23)
    at sketch.js:23
```

I am very interrested in this project however the start seem a bit harsh :D 
Is there a stable branch ?

**Comment by emphasize** [comment]
```
var cp = new RabbitEar.CreasePattern();
cp.axiom1([0, 0.5], [0.5, 1]).valley();
var origami = RabbitEar.Origami(cp);
```

should do the trick. There's some rewriting (resp. adding functionality)  going on, so you have to muddle through. Look at the (current repos') examples, this will help a bit. But since the authors works heavily with preexisting patterns its not easy to get the basics straight away.

**Comment by robbykraft** [comment]
My deepest apologies for not being responsive.
You are right I was not hosting a stable development environment. I still had to learn basic dev ops.
In the meantime the entire library has been re-written from the ground up in this past year. I'm making sure that the master branch is always stable now. the repo's readme is directed at developers instead of users now too https://github.com/robbykraft/Origami/blob/e83d5a7dc22d2ba5d459cc33a04cec453138ffca/readme.md thank you and sorry again!
