### ISSUE TITLE
Is Node compatibility possible or on the radar? 

### ISSUE THREAD

**Issue by etjones** [robbykraft/Origami#27]
This seems like such a lovely, capable system! Congratulations and thank you! 

I see that there's an [npm package](https://www.npmjs.com/package/rabbit-ear) defined, but it looks like it's still depending on being run in a browser. Do you see that as an ongoing design plan? 

```
% ) npm i rabbit-ear
% ) node
> let RabbitEar = require('rabbit-ear')
ReferenceError: window is not defined
    at ${workspaceFolder}/node_modules/rabbit-ear/RabbitEar.js:5490:5
    at ${workspaceFolder}/node_modules/rabbit-ear/RabbitEar.js:2:68
>
```

**Comment by robbykraft** [comment]
yes, in fact! happy to say i'm finally learning node. i've started releasing smaller projects (things which are part of rabbit ear in fact) to build up to this one.

first success: https://www.npmjs.com/package/svg-segmentize

and other components of this project which as of these past couple weeks are now node-compatible (if not yet hosted on npm)

- https://github.com/robbykraft/FOLD_SVG
- https://github.com/robbykraft/Math

i also took a first pass at solving the isomorphism issue. svg-segmentize solves 3 problems:

- DOMParser
- XMLSerializer
- document

unclear if i solved it elegantly or not but it seems to be working! and these are directly relevant to the larger Rabbit Ear conversion. which btw, i'd like to release something to npm in a month, something meaning it might be a reduced feature set but at least running. that's the plan at least!

**Comment by robbykraft** [comment]
happy to say this is done. https://www.npmjs.com/package/rabbit-ear
progress will continue.
